{% set name = "monetio" %}
{% set version = "0.1" %}

package:
  name: monetio
  version: {{ version }}

source:
  git_url: https://github.com/noaa-oar-arl/monetio.git
  git_tag: develop
  #url: https://github.com/noaa-oar-arl/MONET/archive/v2.1.3-dev.2.tar.gz
  # sha256: 7027a0478cab0f877ebc7e412a0249d0578c0944fab4da6f341175995b957931

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
  run:
    - git
    - python
    - numpy
    - pandas
    - xarray
    - dask
    - s3fs

about:
  home: https://monet-arl.readthedocs.io
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - Input / Output

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - bbakernoaa
