{% set name = "monetio" %}
{% set version = "0.1" %}

package:
  name: monetio
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/{{ name }}/archive/v0.1.tar.gz
  sha256: 0bd6fc39d9ad7ab0899f5700fbe99715f87aedaf8edb50c5adaef36a984024fc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
  host:
    - python
  run:
    - python
    - numpy
    - pandas
    - xarray
    - dask
    - s3fs
    - pyresample
    - joblib

about:
  home: https://monetio-arl.readthedocs.io
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - Input / Output

extra:
  recipe-maintainers:
    - bbakernoaa
