{% set name = "monetio" %}
{% set version = "0.1" %}

package:
  name: monetio
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/{{ name }}.git
  # sha256: 7027a0478cab0f877ebc7e412a0249d0578c0944fab4da6f341175995b957931

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
  host:
    - python
  run:
    - python
    - numpy
    - pandas
    - xarray
    - dask
    - s3fs

about:
  home: https://monetio-arl.readthedocs.io
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - Input / Output

extra:
  recipe-maintainers:
    - bbakernoaa
