[build-system]
requires = ["setuptools>=39.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
known_first_party = "monetio"
profile = "black"
line_length = 100

[tool.pytest.ini_options]
filterwarnings = [
   "ignore:The distutils package is deprecated:DeprecationWarning:joblib.backports"
]
