name: CI

on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [stable, develop]
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Conda packages
        uses: actions/cache@v2.1.7
        env:
          CACHE_NUMBER: 0 # increase to reset cache if the environment.yml has not changed
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment-dev.yml') }}

      - name: Set up Python (Conda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          activate-environment: monetio-dev
          environment-file: environment-dev.yml
          use-only-tar-bz2: true # needs to be set for caching to work

      - name: Check Conda
        run: |
          conda info -a
          conda list

      - name: Test with pytest
        run: pytest

  docs:
    name: Check docs build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python (Conda)
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          channels: conda-forge,nodefaults
          activate-environment: monetio-docs
          environment-file: docs/environment-docs.yml

      - name: linkcheck
        run: sphinx-build -b linkcheck docs docs/_build/linkcheck

      - name: sphinx-build -W
        run: sphinx-build -b html -W docs docs/_build/html
