name: Lint

on:
  push:
    branches: [stable, develop]
  pull_request:
    branches: [stable, develop]

jobs:
  linting:
    name: pre-commit
    runs-on: ubuntu-latest
    if: github.repository == 'noaa-oar-arl/monetio'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: pre-commit/action@v2.0.3
